version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A my_django_project worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - app_network

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    networks:
      - app_network

volumes:
  pg_data:
  redis_data:

networks:
  app_network:
    driver: bridge